Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: true

    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 81, host: 8081

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus   = 1
    end

    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y php-common libapache2-mod-php php-cli
        sudo apt-get install -y apache2
        sudo apt-get update
    
        sudo mkdir -p /var/www/html   
        sudo chown vagrant:vagrant /var/www/html

        sudo systemctl restart apache2

    SHELL

    config.vm.provision "file", 
        source: "index.html", 
        destination: "/tmp/"

    config.vm.provision "file", 
        source: "index.php", 
        destination: "/tmp/"

    config.vm.provision "shell",
        inline: "mv /tmp/index.html /var/www/html/"

    config.vm.provision "shell",
        inline: "mv /tmp/index.php /var/www/html/"


        config.vm.provision "shell", inline: <<-SHELL
        sudo bash -c 'echo "Listen 81" >> /etc/apache2/ports.conf'
        
        sudo bash -c 'echo "<VirtualHost *:81>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/index.php


        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        </VirtualHost>" > /etc/apache2/sites-available/000-default.conf'

        sudo systemctl restart apache2

    SHELL

end