Vagrant.configure("2") do |config|

    config.vm.synced_folder  ".", "/vagrant", disabled: false

    #VM1
    config.vm.define "vm1" do |vm1|
        vm1.vm.box = "generic/debian11"
        vm1.vm.hostname = "vm1"
        vm1.vm.network "private_network", ip: "192.168.56.3"

        vm1.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook_vm1.yml"
        end
    end
    
    #VM2
    config.vm.define "vm2" do |vm2|
        vm2.vm.box = "generic/debian11"
        vm2.vm.hostname = "vm2"
        vm2.vm.network "private_network", ip: "192.168.56.4"

        vm2.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook_vm2.yml"
        end
    end

    #VM3
    config.vm.define "vm3" do |vm3|
        vm3.vm.box = "generic/debian11"
        vm3.vm.hostname = "vm3"
        vm3.vm.network "private_network", ip: "192.168.56.5"

        vm3.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook_vm3.yml"
        end
    end
end